# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>
  pool:     5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: learning_development

test:
  <<: *default
  database: learning_test

production:
  <<: *default
  database: learning_production
  pool: 15